// This file was auto-generated by the D2DEZ asset manager from:
// "#PATH#"
#pragma once
#include <Windows.h>
#include "EZAudioClient.h"

constexpr UINT32 #NAME#_Length = #LENGTH#;
constexpr const BYTE #NAME#_Buffer[] = #BUFFER#;

constexpr EZ::AudioAsset #NAME#_Asset  = { #NAME#_Length, #NAME#_Buffer };