// This file was auto-generated by the D2DEZ asset manager from:
// "#PATH#"
#pragma once
#include <Windows.h>
#include <D2D1.h>
#include "EZRenderer.h"

constexpr UINT32 #NAME#_Width = #WIDTH#;
constexpr UINT32 #NAME#_Height = #HEIGHT#;
constexpr const BYTE #NAME#_Buffer[] = #BUFFER#;

constexpr EZ::BitmapAsset #NAME#_Asset  = { #NAME#_Width , #NAME#_Height, #NAME#_Buffer };