// This file was auto-generated by the D2DEZ asset manager from:
// "#PATH#"
#pragma once
#include <Windows.h>
#include <D2D1.h>
#include "EZRenderer.h"

constexpr UINT32 #NAME#_Width = #WIDTH#;
constexpr UINT32 #NAME#_Height = #HEIGHT#;
constexpr UINT32 #NAME#_Stride = #WIDTH#  * 4;
constexpr DXGI_FORMAT #NAME#_PixelFormat = DXGI_FORMAT_B8G8R8A8_UNORM;
constexpr D2D1_ALPHA_MODE #NAME#_AlphaMode = D2D1_ALPHA_MODE_PREMULTIPLIED;
constexpr FLOAT #NAME#_DpiX = 0.0f;
constexpr FLOAT #NAME#_DpiY = 0.0f;
constexpr const BYTE #NAME#_Buffer[] = #BUFFER#;

constexpr EZ::BitmapAsset #NAME#_Asset  = { #NAME#_Width , #NAME#_Height, #NAME#_Stride, #NAME#_PixelFormat, #NAME#_AlphaMode, #NAME#_DpiX, #NAME#_DpiY, #NAME#_Buffer };